"""Readable closeout for the fixed latent-output comparison."""
from pathlib import Path
from .stage5e3_artifacts import read, freeze, freeze_json


def fmt(interval):
    if interval['point'] is None:
        return 'not estimable'
    return f"{interval['point']:.3f} [{interval['low']:.3f}, {interval['high']:.3f}]"


def main(root):
    run = root / 'reports/style_embedding_control/v1'
    results = read(run / 'results.json')
    diagnosis = results['diagnosis']
    lines = ['# Frozen Discogs latent-output control', '', f'**{diagnosis}**', '',
        'This is a fixed, non-learned comparison on exposed development evidence. The owner confirmed the three questioned recordings. No source audio, historical ratings, previous verdicts or production behavior changed.', '',
        'One frozen Discogs-EffNet model produced all full-song patch embeddings. Raw 1280-D patch vectors were averaged and the song mean L2-normalized; song similarity is cosine. There was no learned projection, fusion, model selection or lambda tuning.', '',
        '## Matched grouped comparisons', '',
        'Values are anchor-macro strict preference accuracy with descriptive 95% anchor bootstrap intervals. The same three frozen heldout groups and eligible human constraints are used for every method. Ratings of 3 remain ordinal observations but are excluded from binary good/bad discrimination.', '']
    for rubric in ('playlist', 'holistic'):
        lines += [f'### {rubric}', '', '| Slice | Anchors | Latent cosine | Label 1−JS | CLAP D | CLAP C |', '|---|---:|---:|---:|---:|---:|']
        for variant, row in results[rubric]['grouped'].items():
            perf = row['performance']
            lines.append(f"| {variant} | {row['anchors']} | {fmt(perf['latent'])} | {fmt(perf['labels'])} | {fmt(perf['D'])} | {fmt(perf['C'])} |")
        lines += ['', '| Slice | Latent minus labels | Latent minus D | Latent minus C |', '|---|---:|---:|---:|']
        for variant, row in results[rubric]['grouped'].items():
            delta = row['paired_latent_delta']
            lines.append(f"| {variant} | {fmt(delta['labels'])} | {fmt(delta['D'])} | {fmt(delta['C'])} |")
        lines += ['', '| Fold | Preferences | Anchors | Latent | Labels | D | C |', '|---|---:|---:|---:|---:|---:|---:|']
        for fold in results[rubric]['folds']:
            row = fold['metrics']['ordinal']
            values = ' | '.join(f"{row[n]['macro']:.3f}" if row[n]['macro'] is not None else 'null' for n in ('latent', 'labels', 'D', 'C'))
            lines.append(f"| {fold['fold']} | {row['latent']['preferences']} | {row['latent']['anchors']} | {values} |")
        lines += ['']
    lines += ['## Good versus bad, all existing rated pairs', '',
        'This secondary AUC asks whether good (4–5) beats bad (1–2) for a shared anchor. It does not measure the precision of new unreviewed Top-5 neighbors.', '',
        '| Rubric | Method | Anchors | AUC |', '|---|---|---:|---:|']
    for rubric in ('playlist', 'holistic'):
        for name, row in results[rubric]['all_pair_discrimination'].items():
            lines.append(f"| {rubric} | {name} | {row['anchors']} | {fmt(row['macro_auc'])} |")
    lines += ['', '## Interpretation limits', '',
        'The primary advancement rule requires a latent-minus-label gain of at least 0.03 with descriptive lower bound above zero. A candidate for a future complementarity test additionally meets that rule versus D. Neither label guarantees an advantage over C; its results remain visible. Standalone performance does not prove incremental value when combined with CLAP.', '',
        'Latent cosine versus label JS changes both output and metric. It therefore tests a practical latent alternative, not information loss in the classifier head in isolation. CLAP comparisons additionally change representation construction and coverage. Shared candidates, few folds, prior exposure, unknown pretraining membership and a single reviewer constrain generalization.', '',
        'Owner confirmation resolves the intended-recording question. Artist aliases are not independently established; the three-case exclusion sensitivity preserves that uncertainty. No new human review is generated by this run.', '',
        'See `verification.json` for extraction, zero-inference replay, synthetic checks and test counts. `artifact_manifest.json` and `source_manifest.json` hash the complete evidence and implementation. See `docs/style_embedding_control.md` for commands.', '']
    freeze(run / 'report.md', '\n'.join(lines).encode())
    print(diagnosis)


if __name__ == '__main__':
    main(Path.cwd())
